# Generated by Django 5.0.6 on 2024-06-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_choice_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='question',
        ),
        migrations.AddField(
            model_name='tags',
            name='question',
            field=models.ManyToManyField(related_name='tags', to='polls.question'),
        ),
    ]
